# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailing.ui'
#
# Created: Thu Sep 16 11:01:03 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 416)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Subject = QtGui.QLabel(self.centralwidget)
        self.label_Subject.setObjectName("label_Subject")
        self.gridLayout_2.addWidget(self.label_Subject, 0, 0, 1, 1)
        self.lineEdit_Subject = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Subject.setObjectName("lineEdit_Subject")
        self.gridLayout_2.addWidget(self.lineEdit_Subject, 0, 1, 1, 1)
        self.label_PlainText = QtGui.QLabel(self.centralwidget)
        self.label_PlainText.setObjectName("label_PlainText")
        self.gridLayout_2.addWidget(self.label_PlainText, 1, 0, 1, 1)
        self.lineEdit_PlainText = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_PlainText.setObjectName("lineEdit_PlainText")
        self.gridLayout_2.addWidget(self.lineEdit_PlainText, 1, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Html = QtGui.QLabel(self.centralwidget)
        self.label_Html.setObjectName("label_Html")
        self.verticalLayout.addWidget(self.label_Html)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.textEdit_Html = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_Html.setObjectName("textEdit_Html")
        self.gridLayout_2.addWidget(self.textEdit_Html, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_User = QtGui.QLabel(self.centralwidget)
        self.label_User.setObjectName("label_User")
        self.gridLayout.addWidget(self.label_User, 0, 0, 1, 1)
        self.comboBox_User = QtGui.QComboBox(self.centralwidget)
        self.comboBox_User.setObjectName("comboBox_User")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.comboBox_User.addItem("")
        self.gridLayout.addWidget(self.comboBox_User, 0, 1, 1, 1)
        self.label_Password = QtGui.QLabel(self.centralwidget)
        self.label_Password.setObjectName("label_Password")
        self.gridLayout.addWidget(self.label_Password, 1, 0, 1, 1)
        self.lineEdit_Password = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.gridLayout.addWidget(self.lineEdit_Password, 1, 1, 1, 1)
        self.label_List = QtGui.QLabel(self.centralwidget)
        self.label_List.setObjectName("label_List")
        self.gridLayout.addWidget(self.label_List, 2, 0, 1, 1)
        self.comboBox_List = QtGui.QComboBox(self.centralwidget)
        self.comboBox_List.setObjectName("comboBox_List")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.comboBox_List.addItem("")
        self.gridLayout.addWidget(self.comboBox_List, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_Subject.setBuddy(self.lineEdit_Subject)
        self.label_PlainText.setBuddy(self.lineEdit_PlainText)
        self.label_Html.setBuddy(self.textEdit_Html)
        self.label_User.setBuddy(self.comboBox_User)
        self.label_Password.setBuddy(self.lineEdit_Password)
        self.label_List.setBuddy(self.comboBox_List)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), MainWindow.close)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), MainWindow.sendEmail)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_Subject, self.lineEdit_PlainText)
        MainWindow.setTabOrder(self.lineEdit_PlainText, self.textEdit_Html)
        MainWindow.setTabOrder(self.textEdit_Html, self.comboBox_User)
        MainWindow.setTabOrder(self.comboBox_User, self.lineEdit_Password)
        MainWindow.setTabOrder(self.lineEdit_Password, self.comboBox_List)
        MainWindow.setTabOrder(self.comboBox_List, self.buttonBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Subject.setText(QtGui.QApplication.translate("MainWindow", "Subject:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_PlainText.setText(QtGui.QApplication.translate("MainWindow", "Plain Text:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Html.setText(QtGui.QApplication.translate("MainWindow", "HTML:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_User.setText(QtGui.QApplication.translate("MainWindow", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_User.setItemText(0, QtGui.QApplication.translate("MainWindow", "letsdancebanda", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_User.setItemText(1, QtGui.QApplication.translate("MainWindow", "bandaletsdancelp", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_User.setItemText(2, QtGui.QApplication.translate("MainWindow", "bandaletsdancems", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_User.setItemText(3, QtGui.QApplication.translate("MainWindow", "bandaletsdancerh", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_User.setItemText(4, QtGui.QApplication.translate("MainWindow", "bandaletsdancece", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Password.setText(QtGui.QApplication.translate("MainWindow", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_List.setText(QtGui.QApplication.translate("MainWindow", "Lista:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(0, QtGui.QApplication.translate("MainWindow", "Edu", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(1, QtGui.QApplication.translate("MainWindow", "Banda", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(2, QtGui.QApplication.translate("MainWindow", "Friends", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(3, QtGui.QApplication.translate("MainWindow", "La Playa 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(4, QtGui.QApplication.translate("MainWindow", "La Playa 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(5, QtGui.QApplication.translate("MainWindow", "Passeio Público", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(6, QtGui.QApplication.translate("MainWindow", "Hum Grill", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(7, QtGui.QApplication.translate("MainWindow", "Let\'s Dance", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_List.setItemText(8, QtGui.QApplication.translate("MainWindow", "Juliana", None, QtGui.QApplication.UnicodeUTF8))

